// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Note: Supabase client does not support configuring DB pool size from the browser.
// Increase the connection pool size in Supabase Edge Functions via the SUPABASE_POOL_SIZE env variable.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Note: localStorage is used for session persistence.
    // XSS risks are mitigated by the strict Content Security Policy (CSP) 
    // and input sanitization (DOMPurify) implemented in the application.
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});