project_id = "rtvrdbbojqsrbkngnjgq"

[functions.send-contact-email]
verify_jwt = false

[functions.health_check]
verify_jwt = false

[functions.fetch-auto-news]
verify_jwt = false

[functions.phone-verification]
verify_jwt = true

[functions.send-scholarship-alerts]
verify_jwt = true

[functions.send-registration-status-email]
verify_jwt = true

[functions.send-admin-invite]
verify_jwt = true

[functions.notify-pending-review]
verify_jwt = true

[functions.send-material-status-email]
verify_jwt = true

[functions.validate-ticket]
verify_jwt = true

[functions.notify-matching-events]
verify_jwt = true

[functions.send-personalized-notification]
verify_jwt = true

[functions.compress-pdf]
verify_jwt = true

[functions.send-web-push]
verify_jwt = true

[functions.send-scholarship-reminders]
verify_jwt = true

[functions.fetch-india-scholarships]
verify_jwt = true

[functions.send-deadline-reminders]
verify_jwt = true

[functions.send-registration-email]
verify_jwt = true

[functions.sync-to-sheets]
verify_jwt = true

[functions.send-volunteer-notification]
verify_jwt = true

[functions.scan-upi]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.prerender]
verify_jwt = false

[functions.submit-to-google-indexing]
verify_jwt = true

[functions.send-brevo-email]
verify_jwt = true

[functions.send-ticket-email]
verify_jwt = true

